# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20170808_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
