# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20170808_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
